In [5]:
## importatant libraries
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import xgboost 
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [7]:
data1 = pd.read_csv('kenya_land_registry_parcels_messy.csv')
data1.head()

,record_id,title_number,old_title_number,county,sub_county,ward,nearest_town,registry_office,latitude,longitude,...,disputed,court_case_no,land_ownership_source,digitisation_status,distance_to_tarmac_km,flood_risk,soil_type,rainfall_zone,remarks,suspected_fraud_flag
0,LR0091025,NAIROBI/KARURA/18334,NaN,Nairobi,Kamukunji,Kamukunji North,Nairobi,Nairobi Lands Registry,-1.2873493,36.8190755,...,Y,ELC Petition E381 of 2018,Manual Ledger,Migrated,NaN,Low,Red volcanic,Zone V,NaN,0.0
1,LR0096119,KAKAMEGA/KANYARIRI/94313,KAKAMEGA/WEST/91089,Kakamega,Mumias East,Mumias South,Mumias,Kakamega Lands Registry,0.301589,34.755907,...,N,NaN,Legacy Registry,Partial,NaN,NaN,Sandy loam,Zone V,NaN,0.0
2,LR0083166,TURKANA/WEST/20510,NaN,Turkana,Loima,Loima South,Lodwar,Turkana Lands Registry,3.43985358,35.14880629,...,N,NaN,Ardhisasa,Partial,NaN,Low,Alluvial,Zone III,ukubwa haulingani na deed plan,0.0
3,LR0001529,MAKUENI/WEST/6316,NaN,Makueni,Kibwezi West,Kibwezi South,Emali,Makueni Lands Registry,-1.86408724,37.43876570,...,N,NaN,Settlement Scheme,Migrated,22.72,Low,NaN,Zone V,NaN,0.0
4,LR0085017,IR 65526,NaN,Mombasa,Kisauni,Kisauni Township,Mombasa,Mombasa Lands Registry,-4.0054662,39.6261299,...,N,NaN,Ardhisasa,Migrated,14.55,Medium,Murram,Zone I,Reg. error corrected 04/12/21,0.0

In [8]:
data2 = pd.read_csv('kenya_land_registry_parcels_messy.csv')
data2.head()

,record_id,title_number,old_title_number,county,sub_county,ward,nearest_town,registry_office,latitude,longitude,...,disputed,court_case_no,land_ownership_source,digitisation_status,distance_to_tarmac_km,flood_risk,soil_type,rainfall_zone,remarks,suspected_fraud_flag
0,LR0091025,NAIROBI/KARURA/18334,NaN,Nairobi,Kamukunji,Kamukunji North,Nairobi,Nairobi Lands Registry,-1.2873493,36.8190755,...,Y,ELC Petition E381 of 2018,Manual Ledger,Migrated,NaN,Low,Red volcanic,Zone V,NaN,0.0
1,LR0096119,KAKAMEGA/KANYARIRI/94313,KAKAMEGA/WEST/91089,Kakamega,Mumias East,Mumias South,Mumias,Kakamega Lands Registry,0.301589,34.755907,...,N,NaN,Legacy Registry,Partial,NaN,NaN,Sandy loam,Zone V,NaN,0.0
2,LR0083166,TURKANA/WEST/20510,NaN,Turkana,Loima,Loima South,Lodwar,Turkana Lands Registry,3.43985358,35.14880629,...,N,NaN,Ardhisasa,Partial,NaN,Low,Alluvial,Zone III,ukubwa haulingani na deed plan,0.0
3,LR0001529,MAKUENI/WEST/6316,NaN,Makueni,Kibwezi West,Kibwezi South,Emali,Makueni Lands Registry,-1.86408724,37.43876570,...,N,NaN,Settlement Scheme,Migrated,22.72,Low,NaN,Zone V,NaN,0.0
4,LR0085017,IR 65526,NaN,Mombasa,Kisauni,Kisauni Township,Mombasa,Mombasa Lands Registry,-4.0054662,39.6261299,...,N,NaN,Ardhisasa,Migrated,14.55,Medium,Murram,Zone I,Reg. error corrected 04/12/21,0.0

In [9]:
df=data1.merge(data2, how='inner', on='record_id')
df

,record_id,title_number_x,old_title_number_x,county_x,sub_county_x,ward_x,nearest_town_x,registry_office_x,latitude_x,longitude_x,...,disputed_y,court_case_no_y,land_ownership_source_y,digitisation_status_y,distance_to_tarmac_km_y,flood_risk_y,soil_type_y,rainfall_zone_y,remarks_y,suspected_fraud_flag_y
0,LR0091025,NAIROBI/KARURA/18334,NaN,Nairobi,Kamukunji,Kamukunji North,Nairobi,Nairobi Lands Registry,-1.2873493,36.8190755,...,Y,ELC Petition E381 of 2018,Manual Ledger,Migrated,NaN,Low,Red volcanic,Zone V,NaN,0.0
1,LR0096119,KAKAMEGA/KANYARIRI/94313,KAKAMEGA/WEST/91089,Kakamega,Mumias East,Mumias South,Mumias,Kakamega Lands Registry,0.301589,34.755907,...,N,NaN,Legacy Registry,Partial,NaN,NaN,Sandy loam,Zone V,NaN,0.0
2,LR0083166,TURKANA/WEST/20510,NaN,Turkana,Loima,Loima South,Lodwar,Turkana Lands Registry,3.43985358,35.14880629,...,N,NaN,Ardhisasa,Partial,NaN,Low,Alluvial,Zone III,ukubwa haulingani na deed plan,0.0
3,LR0001529,MAKUENI/WEST/6316,NaN,Makueni,Kibwezi West,Kibwezi South,Emali,Makueni Lands Registry,-1.86408724,37.43876570,...,N,NaN,Settlement Scheme,Migrated,22.72,Low,NaN,Zone V,NaN,0.0
4,LR0085017,IR 65526,NaN,Mombasa,Kisauni,Kisauni Township,Mombasa,Mombasa Lands Registry,-4.0054662,39.6261299,...,N,NaN,Ardhisasa,Migrated,14.55,Medium,Murram,Zone I,Reg. error corrected 04/12/21,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125755,LR0048057,KILIFI/SUB LOC 2/1418,NaN,Kilifi,Kilifi North,Kilifi Central,Mtwapa,Kilifi Lands Registry,-3.464971,39.621469,...,N,NaN,Ardhisasa,Not Migrated,NaN,Medium,Murram,Zone II,NaN,0.0
125756,LR0059012,I.R. 23386,NaN,MURANG'A,Kandara,Kandara East,Murang'a,NaN,307265,9927735,...,N,NaN,Adjudication,Migrated,2.08,Medium,Clay,ASAL,Awaiting survey,0.0
125757,LR0077050,I.R. 60958,NaN,Turkana,Loima,Loima South,Lodwar,Turkana Lands Registry,3.91628,36.74509,...,N,NaN,Ardhisasa,Migrated,10.42,Low,Black cotton,NaN,Awaiting survey,0.0
125758,LR0067225,KAKAMEGA/KIRIAINI/63846,KAKAMEGA/LOWER/41989,Kakamega,Mumias East,NaN,Mumias,Kakamega Lands Registry,0.23658,34.86661,...,N,NaN,Ardhisasa,Migrated,19.31,Low,Red volcanic,Zone II,Ownership in dispute - family,0.0
125759,LR0071531,UASIN GISHU/KANYARIRI/88524,NaN,Uasin Gishu,Soy,Soy West,Eldoret,Uasin Gishu Lands Registry,"0°31'40.2""N","35°17'2.1""E",...,N,NaN,Settlement Scheme,Not Migrated,NaN,Medium,Black cotton,ASAL,NaN,0.0